name: Publicar Action
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Construir o projeto
        run: cargo build --release

      - name: Criar release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/git-rewards-action