name: Publicar Action
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Construir o projeto
        run: cargo build --release

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar tag
        id: create_tag
        run: |
          echo "Criando nova tag..."
          TAG="v1.$(date +'%Y%m%d%H%M%S')"
          git tag $TAG
          git push origin $TAG
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Criar release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: target/release/git-rewards-action
